import { spawnSync } from 'node:child_process';
import { chmodSync, copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { RULE_NAMES } from '@voidcorp/hook-runner';
import {
  CODEX_FLOOR_SCRIPTS,
  CODEX_HOOKS_DIR,
  codexFloorDrift,
  codexFloorHealth,
  codexHookBootstrap,
  compileCodexHooksManifest,
  referencedScripts,
  refreshCodexFloor,
  wireCodexFloor,
} from './codex-floor.js';

// The real shipped template — the single source the CLI compiles at init time.
// Reading it here makes the drift guard meaningful: adding a hook to the
// template without staging its script fails this suite.
const here = dirname(fileURLToPath(import.meta.url));
const CORE_ROOT = resolve(here, '..', '..', '..', 'core');
const templatePath = resolve(CORE_ROOT, 'codex', 'hooks.json');
const template = readFileSync(templatePath, 'utf8');

describe('compileCodexHooksManifest', () => {
  it('replaces every VOID_HOOKS_DIR placeholder with a runner lookup from the session cwd', () => {
    const out = compileCodexHooksManifest(template);
    // biome-ignore lint/suspicious/noTemplateCurlyInString: asserting the literal placeholder is gone.
    expect(out).not.toContain('${VOID_HOOKS_DIR}');
    for (const command of compiledCommands(out)) {
      expect(command.startsWith('node -e "')).toBe(true);
      expect(command).toContain(codexHookBootstrap('_void-hook.mjs'));
    }
    expect(out).toContain('enforce dangerous-command');
  });

  it('produces valid JSON', () => {
    expect(() => JSON.parse(compileCodexHooksManifest(template))).not.toThrow();
  });

  it('emits only top-level fields accepted by the Codex hooks schema', () => {
    const manifest = JSON.parse(compileCodexHooksManifest(template)) as Record<string, unknown>;
    expect(Object.keys(manifest).sort()).toEqual(['description', 'hooks']);
    expect(manifest.description).toMatch(/Generated by `void-machine init`/);
    expect(manifest).not.toHaveProperty('$comment');
  });

  it('throws on a template that is valid JSON but not an object', () => {
    expect(() => compileCodexHooksManifest('42')).toThrow(/not a JSON object/);
    expect(() => compileCodexHooksManifest('null')).toThrow(/not a JSON object/);
    expect(() => compileCodexHooksManifest('[1,2]')).toThrow(/not a JSON object/);
  });

  it('refuses a placeholder outside the node-runner command shape', () => {
    // biome-ignore lint/suspicious/noTemplateCurlyInString: a placeholder shape to refuse.
    const command = 'sh "${VOID_HOOKS_DIR}/x.sh"';
    const corrupt = JSON.stringify({
      hooks: { Stop: [{ hooks: [{ type: 'command', command }] }] },
    });
    expect(() => compileCodexHooksManifest(corrupt)).toThrow(/unsupported hook command/);
  });

  // DEV-918: the manifest is versioned, so a path that belongs to the machine
  // that ran init breaks every other clone, worktree and CI checkout.
  it('never embeds an absolute path', () => {
    for (const command of compiledCommands(compileCodexHooksManifest(template))) {
      expect(command).not.toMatch(ABSOLUTE_PATH);
    }
    expect(JSON.parse(compileCodexHooksManifest(template)).description).not.toMatch(ABSOLUTE_PATH);
  });

  // Codex runs a hook through the session shell: sh, bash or zsh on POSIX,
  // PowerShell or cmd.exe on Windows. A command that uses none of their
  // expansion characters means the same thing to all five.
  it('uses no character that any Codex hook shell would expand', () => {
    for (const command of compiledCommands(compileCodexHooksManifest(template))) {
      expect(command).not.toMatch(/[$%`\\!]/);
      expect(command.split('"')).toHaveLength(3);
    }
  });
});

const ABSOLUTE_PATH = /(^|[\s"'(=,])(\/|[A-Za-z]:[\\/]|\\\\)/;

function compiledCommands(manifest: string): string[] {
  const parsed = JSON.parse(manifest) as {
    hooks: Record<string, Array<{ hooks: Array<{ command: string }> }>>;
  };
  return Object.values(parsed.hooks).flatMap((groups) =>
    groups.flatMap((group) => group.hooks.map((hook) => hook.command)),
  );
}

describe('safety-floor matcher coverage', () => {
  /** PreToolUse entries as (rule or script basename -> matcher) pairs. */
  function preToolUseMatchers(): Map<string, string> {
    const manifest = JSON.parse(compileCodexHooksManifest(template));
    const pairs = new Map<string, string>();
    for (const entry of manifest.hooks.PreToolUse as {
      matcher: string;
      hooks: { command: string }[];
    }[]) {
      for (const hook of entry.hooks) {
        const rule = hook.command.match(/\benforce ([a-z-]+)\b/)?.[1];
        const script = hook.command.match(/([A-Za-z0-9_-]+\.sh)\b/)?.[1];
        pairs.set(rule ?? script ?? '', entry.matcher);
      }
    }
    return pairs;
  }

  // The matcher is the load-bearing part: if it misses the tool Codex actually
  // emits, the hook never fires and its enforcement is silently dead. The two
  // surfaces have different tool names, so they are asserted separately.
  it('matches the Bash tool name documented by Codex, and keeps legacy shell', () => {
    const matcher = preToolUseMatchers().get('dangerous-command');
    expect(matcher).toContain('Bash');
    expect(matcher).toContain('shell');
  });

  it('never names Bash without also naming legacy shell', () => {
    for (const m of preToolUseMatchers().values()) {
      if (m.includes('Bash')) expect(m).toContain('shell');
    }
  });

  // Derived from RULE_NAMES rather than spelled out again. Written by hand, this
  // list meant a rule could reach the runner and be wired on neither runtime
  // without one test going red: it proved only that somebody had once typed the
  // same twelve names twice.
  const SHELL_RULES: readonly string[] = ['dangerous-command'];
  const FILE_EDIT_RULES = RULE_NAMES.filter((rule) => !SHELL_RULES.includes(rule));

  it('matches Bash and legacy shell on every shell rule', () => {
    const matchers = preToolUseMatchers();
    for (const rule of SHELL_RULES) {
      expect(matchers.get(rule), `${rule} must be wired`).toMatch(/Bash\|shell/);
    }
  });

  // Codex edits files through apply_patch; a matcher stuck on Claude's
  // Edit|Write would leave every content-scanning hook dead on that runtime.
  it('covers apply_patch on every file-edit hook', () => {
    const matchers = preToolUseMatchers();
    for (const rule of FILE_EDIT_RULES) {
      expect(matchers.get(rule), `${rule} must be wired`).toBeDefined();
      expect(matchers.get(rule), `${rule} must match apply_patch`).toContain('apply_patch');
    }
  });

  it('runs every inline rule through the portable Node bundle', () => {
    const manifest = compileCodexHooksManifest(template);
    for (const rule of RULE_NAMES) {
      expect(manifest).toContain(`\\" enforce ${rule} codex`);
    }
  });
});

describe('referencedScripts drift guard', () => {
  it('stages only the self-contained Node runner', () => {
    expect(CODEX_FLOOR_SCRIPTS).toEqual(['_void-hook.mjs', '_syntax-worker.cjs']);
  });

  it('every script the template invokes is in the staged floor set', () => {
    const referenced = referencedScripts(template);
    expect(referenced.length).toBeGreaterThan(0);
    for (const script of referenced) {
      expect(CODEX_FLOOR_SCRIPTS).toContain(script);
    }
  });

  it('never throws on a malformed (scalar/null) manifest — returns no scripts', () => {
    expect(referencedScripts('42')).toEqual([]);
    expect(referencedScripts('null')).toEqual([]);
    expect(referencedScripts('not json at all')).toEqual([]);
  });
});

describe('wireCodexFloor', () => {
  it('stages every floor script and writes a valid, placeholder-free manifest', async () => {
    const project = mkdtempSync(join(tmpdir(), 'void codex floor '));
    await wireCodexFloor(project, CORE_ROOT);

    for (const script of CODEX_FLOOR_SCRIPTS) {
      expect(existsSync(join(project, CODEX_HOOKS_DIR, script))).toBe(true);
    }
    expect(statSync(join(project, CODEX_HOOKS_DIR, '_void-hook.mjs')).mode & 0o100).toBeFalsy();

    const manifest = readFileSync(join(project, '.codex', 'hooks.json'), 'utf8');
    // biome-ignore lint/suspicious/noTemplateCurlyInString: asserting the literal placeholder is gone.
    expect(manifest).not.toContain('${VOID_HOOKS_DIR}');
    expect(() => JSON.parse(manifest)).not.toThrow();
    expect(manifest).not.toContain(project);
    expect(manifest).not.toContain('$(git rev-parse');
    // every referenced script actually landed on disk (no wired-but-absent hook)
    for (const script of referencedScripts(manifest)) {
      expect(existsSync(join(project, CODEX_HOOKS_DIR, script))).toBe(true);
    }
  });

  it('executes the native Node TDD rule from a project subdirectory', async () => {
    const project = mkdtempSync(join(tmpdir(), 'void codex native '));
    await wireCodexFloor(project, CORE_ROOT);
    mkdirSync(join(project, '.void'), { recursive: true });
    writeFileSync(join(project, '.void', 'config.json'), '{}\n');
    mkdirSync(join(project, 'apps', 'web', 'src'), { recursive: true });
    writeFileSync(join(project, 'apps', 'web', 'src', 'Card.tsx'), 'export const Card = 1;\n');
    writeFileSync(join(project, 'apps', 'web', 'src', 'Card.test.tsx'), 'test("Card", () => {});\n');
    const nested = join(project, 'apps', 'web');
    const manifest = JSON.parse(readFileSync(join(project, '.codex', 'hooks.json'), 'utf8'));
    const command = manifest.hooks.PreToolUse
      .flatMap((entry: { hooks: Array<{ command: string }> }) => entry.hooks)
      .find((hook: { command: string }) => hook.command.includes('enforce tdd-order'))
      ?.command;
    expect(command).toBeDefined();

    const result = spawnSync(command, {
      cwd: nested,
      shell: true,
      input: JSON.stringify({
        tool_name: 'apply_patch',
        tool_input: {
          patch: '*** Begin Patch\n*** Update File: apps/web/src/Card.tsx\n@@\n-export const Card = 1;\n+export const Card = 2;\n*** End Patch',
        },
      }),
      encoding: 'utf8',
    });

    expect(result.status, result.stderr).toBe(0);
  });

  it('writes the same manifest whatever the checkout it runs in', async () => {
    const first = mkdtempSync(join(tmpdir(), 'void codex clone a '));
    const second = mkdtempSync(join(tmpdir(), 'void-codex-clone-b-'));
    await wireCodexFloor(first, CORE_ROOT);
    await wireCodexFloor(second, CORE_ROOT);
    expect(readFileSync(join(first, '.codex', 'hooks.json'), 'utf8')).toBe(
      readFileSync(join(second, '.codex', 'hooks.json'), 'utf8'),
    );
  });

  it('fails closed on enforcement and open on lifecycle when no runner is staged', () => {
    const project = mkdtempSync(join(tmpdir(), 'void codex unstaged '));
    const commands = compiledCommands(compileCodexHooksManifest(template));
    const enforce = commands.find((command) => command.endsWith('enforce dangerous-command codex'));
    const lifecycle = commands.find(
      (command) => command.endsWith('lifecycle checkpoint-audit codex'),
    );
    const input = JSON.stringify({ tool_name: 'Bash', tool_input: { command: 'ls' } });

    const options = { cwd: project, shell: true, input, encoding: 'utf8' } as const;
    const blocked = spawnSync(enforce ?? '', options);
    // Exit 0 with a denial: the only refusal PowerShell, Codex's default shell on
    // Windows, does not turn into a failed hook that lets the call through.
    expect(blocked.status).toBe(0);
    expect(blocked.stdout).toMatch(/^[\x20-\x7e]*\n$/);
    expect(JSON.parse(blocked.stdout)).toEqual({
      hookSpecificOutput: {
        hookEventName: 'PreToolUse',
        permissionDecision: 'deny',
        permissionDecisionReason: expect.stringContaining('HOOK_RUNNER_MISSING'),
      },
    });
    expect(blocked.stderr).toContain('HOOK_RUNNER_MISSING');
    const passed = spawnSync(lifecycle ?? '', options);
    expect(passed.status).toBe(0);
    expect(passed.stdout).toBe('');
    expect(passed.stderr).toContain('HOOK_RUNNER_MISSING');
  });

  it('returns the staged-script count and is idempotent', async () => {
    const project = mkdtempSync(join(tmpdir(), 'void-codex-floor-'));
    expect(await wireCodexFloor(project, CORE_ROOT)).toBe(CODEX_FLOOR_SCRIPTS.length);
    await expect(wireCodexFloor(project, CORE_ROOT)).resolves.toBe(CODEX_FLOOR_SCRIPTS.length);
  });

  it('keeps Node assets healthy when npm/pnpm pack strips their executable bit', async () => {
    const src = mkdtempSync(join(tmpdir(), 'void-codex-src-'));
    mkdirSync(join(src, 'hooks'), { recursive: true });
    mkdirSync(join(src, 'codex'), { recursive: true });
    for (const s of CODEX_FLOOR_SCRIPTS) {
      copyFileSync(join(CORE_ROOT, 'hooks', s), join(src, 'hooks', s));
      chmodSync(join(src, 'hooks', s), 0o644); // stripped, as in a packed tarball
    }
    copyFileSync(join(CORE_ROOT, 'codex', 'hooks.json'), join(src, 'codex', 'hooks.json'));

    const project = mkdtempSync(join(tmpdir(), 'void-codex-floor-'));
    await wireCodexFloor(project, src);

    // Node reads the bundle as data; the executable bit is irrelevant.
    expect((await codexFloorHealth(project)).ok).toBe(true);
    expect(statSync(join(project, CODEX_HOOKS_DIR, '_void-hook.mjs')).mode & 0o111).toBeFalsy();
  });
});

describe('codexFloorDrift', () => {
  it('reports a freshly wired floor as in sync (no drift)', async () => {
    const project = mkdtempSync(join(tmpdir(), 'void-codex-drift-'));
    await wireCodexFloor(project, CORE_ROOT);
    expect(await codexFloorDrift(project, CORE_ROOT)).toEqual([]);
  });

  it('flags a never-wired project: every file drifts', async () => {
    const project = mkdtempSync(join(tmpdir(), 'void-codex-drift-'));
    const drift = await codexFloorDrift(project, CORE_ROOT);
    expect(drift).toContain('hooks.json');
    for (const script of CODEX_FLOOR_SCRIPTS) expect(drift).toContain(script);
  });

  it('flags a staged script whose content diverged', async () => {
    const project = mkdtempSync(join(tmpdir(), 'void-codex-drift-'));
    await wireCodexFloor(project, CORE_ROOT);
    writeFileSync(join(project, CODEX_HOOKS_DIR, '_void-hook.mjs'), '// tampered\n');
    const drift = await codexFloorDrift(project, CORE_ROOT);
    expect(drift).toEqual(['_void-hook.mjs']);
  });

  it('ignores a trailing-newline-only difference in the manifest', async () => {
    const project = mkdtempSync(join(tmpdir(), 'void-codex-drift-'));
    await wireCodexFloor(project, CORE_ROOT);
    const manifestPath = join(project, '.codex', 'hooks.json');
    writeFileSync(manifestPath, `${readFileSync(manifestPath, 'utf8').replace(/\n+$/, '')}\n\n\n`);
    expect(await codexFloorDrift(project, CORE_ROOT)).toEqual([]);
  });
});

describe('codexFloorHealth', () => {
  it('reports a freshly wired floor as healthy', async () => {
    const project = mkdtempSync(join(tmpdir(), 'void-codex-health-'));
    await wireCodexFloor(project, CORE_ROOT);
    const health = await codexFloorHealth(project);
    expect(health.ok).toBe(true);
    expect(health.detail).toContain('wired');
  });

  it('flags a missing manifest', async () => {
    const project = mkdtempSync(join(tmpdir(), 'void-codex-health-'));
    const health = await codexFloorHealth(project);
    expect(health.ok).toBe(false);
    expect(health.detail).toContain('missing');
  });

  it('does not crash on a valid-JSON-but-non-object manifest (null or array)', async () => {
    const project = mkdtempSync(join(tmpdir(), 'void-codex-health-'));
    await wireCodexFloor(project, CORE_ROOT);
    for (const scalar of ['null\n', '[1,2]\n', '42\n']) {
      writeFileSync(join(project, '.codex', 'hooks.json'), scalar);
      const health = await codexFloorHealth(project);
      expect(health.ok).toBe(false);
      expect(health.detail).toContain('not a JSON object');
    }
  });

  it('flags invalid JSON', async () => {
    const project = mkdtempSync(join(tmpdir(), 'void-codex-health-'));
    await wireCodexFloor(project, CORE_ROOT);
    writeFileSync(join(project, '.codex', 'hooks.json'), '{ broken');
    const health = await codexFloorHealth(project);
    expect(health.ok).toBe(false);
    expect(health.detail).toContain('not valid JSON');
  });

  it('does not stage shell libraries that the native manifest no longer invokes', async () => {
    const project = mkdtempSync(join(tmpdir(), 'void-codex-health-'));
    await wireCodexFloor(project, CORE_ROOT);
    expect(existsSync(join(project, CODEX_HOOKS_DIR, '_hooklib.sh'))).toBe(false);
    expect((await codexFloorHealth(project)).ok).toBe(true);
  });

  it('keeps a Node entry healthy without an executable bit', async () => {
    const project = mkdtempSync(join(tmpdir(), 'void-codex-health-'));
    await wireCodexFloor(project, CORE_ROOT);
    chmodSync(join(project, CODEX_HOOKS_DIR, '_void-hook.mjs'), 0o644);
    const health = await codexFloorHealth(project);
    expect(health.ok).toBe(true);
  });
});

describe('refreshCodexFloor', () => {
  it('reports fresh and writes nothing when the floor is in sync', async () => {
    const project = mkdtempSync(join(tmpdir(), 'void-codex-refresh-'));
    await wireCodexFloor(project, CORE_ROOT);
    const result = await refreshCodexFloor(project, CORE_ROOT, false);
    expect(result.status).toBe('fresh');
    expect(result.drift).toEqual([]);
  });

  it('previews a re-stage under dry-run without touching the file', async () => {
    const project = mkdtempSync(join(tmpdir(), 'void-codex-refresh-'));
    await wireCodexFloor(project, CORE_ROOT);
    const staged = join(project, CODEX_HOOKS_DIR, '_void-hook.mjs');
    writeFileSync(staged, '# tampered\n');
    const result = await refreshCodexFloor(project, CORE_ROOT, true);
    expect(result.status).toBe('would-refresh');
    expect(result.drift).toEqual(['_void-hook.mjs']);
    expect(readFileSync(staged, 'utf8')).toBe('# tampered\n'); // untouched
  });

  it('re-stages on drift when not a dry-run, restoring the file', async () => {
    const project = mkdtempSync(join(tmpdir(), 'void-codex-refresh-'));
    await wireCodexFloor(project, CORE_ROOT);
    const staged = join(project, CODEX_HOOKS_DIR, '_void-hook.mjs');
    writeFileSync(staged, '# tampered\n');
    const result = await refreshCodexFloor(project, CORE_ROOT, false);
    expect(result.status).toBe('refreshed');
    expect(readFileSync(staged, 'utf8')).not.toBe('# tampered\n');
    expect(await codexFloorDrift(project, CORE_ROOT)).toEqual([]);
  });
});
