// tdd-cover: e2e packages/hook-runner/src/cli.test.ts
import { build } from 'esbuild';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';

// One builder owns the published and source-self-host artifact pair.
// https://esbuild.github.io/api/#bundle, #define, #legal-comments
export async function buildHookRuntime({ root, outfile, writeIdentity = false }) {
  const source = join(root, 'packages/hook-runner/src/enforcement');
  const worker = join(dirname(outfile), '_syntax-worker.cjs');
  const require = createRequire(join(root, 'packages/hook-runner/package.json'));
  const license = readFileSync(require.resolve('@typescript/typescript6/LICENSE.txt'), 'utf8');
  await build({
    absWorkingDir: root, entryPoints: [join(source, 'syntax-worker.ts')],
    bundle: true, platform: 'node', format: 'cjs', target: 'node24',
    minify: true, legalComments: 'inline', outfile: worker,
    footer: { js: `/*! TypeScript (Apache-2.0)\n${license}*/` },
  });
  const bytes = readFileSync(worker);
  const identity = { sha256: createHash('sha256').update(bytes).digest('hex'), bytes: bytes.length };
  if (writeIdentity) writeFileSync(join(source, 'syntax-worker-identity.generated.ts'),
    '// tdd-cover: e2e packages/hook-runner/src/enforcement/syntax-inspection.test.ts\n'
    + `// Generated by scripts/build-runtime.mjs. Do not edit.\nexport const SYNTAX_WORKER_IDENTITY = ${JSON.stringify(identity)};\n`);
  await build({
    absWorkingDir: root, entryPoints: [join(root, 'packages/hook-runner/src/cli.ts')],
    alias: { '@voidcorp/mission-engine/events': join(root, 'packages/mission-engine/src/events/index.ts') },
    bundle: true, platform: 'node', format: 'esm', target: 'node24', outfile,
    // YAML's Node distribution is CommonJS and imports the built-in process module.
    banner: { js: "import { createRequire as createNodeRequire } from 'node:module'; const require = createNodeRequire(import.meta.url);" },
    define: { __VOID_SYNTAX_WORKER_URL__: JSON.stringify('./_syntax-worker.cjs'),
      __VOID_SYNTAX_WORKER_IDENTITY__: JSON.stringify(identity) },
  });
  // Remove esbuild's host-dependent module-path comments from the parent.
  writeFileSync(outfile, `// syntax-worker: ${JSON.stringify(identity)}\n`
    + readFileSync(outfile, 'utf8').replace(/^\/\/ [^\r\n]*\.(?:m?js|tsx?)\r?\n/gm, ''));
}
