/**
 * The product identity has one source, packages/core/data/identity.json. Code reads it; the
 * files that cannot import it (npm manifests, plugin manifests, workflows) repeat it, and this
 * contract is what keeps the repetitions honest, in the spirit of `version:check`.
 *
 * It also retires the names the product carried before: an old slug or an old package name left
 * anywhere outside the historical record would point a reader, a guard or an installer at a
 * repository or a package that is no longer ours.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { PRODUCT_IDENTITY } from '../../packages/hook-runner/src/identity.js';
// @ts-expect-error -- plain ESM script, no types
import { PRODUCT_IDENTITY as SCRIPT_IDENTITY } from '../../scripts/product-identity.mjs';

const ROOT = resolve(import.meta.dirname, '../..');
const { repositorySlug, repositoryUrl, packageName, commands, repository } = PRODUCT_IDENTITY;

/**
 * Names the product no longer answers to. The identity keeps them, because it has to know where an
 * old release lives and which workflow references a rename broke; nothing else may.
 */
const RETIRED_NAMES = [
  ...PRODUCT_IDENTITY.formerRepositorySlugs,
  ...PRODUCT_IDENTITY.formerPackages.map((former) => former.name),
];
const SOURCE = 'packages/core/data/identity.json';

/** The historical record keeps the names it was written with; the rest of the tree may not. */
const HISTORICAL = [
  /^docs\/(decisions-log|plans|specs|audits)\//,
  /^docs\/DECISIONS\.md$/,
  // A migration guide to a released version names the package that version shipped under.
  /^docs\/MIGRATING-[\d.]+\.md$/,
  /(^|\/)CHANGELOG\.md$/,
  /^\.void\/requests\.md$/,
];

/** Released or generated bytes: they change when they are rebuilt, never by hand. */
const GENERATED = [
  /^\.void\/hooks\//,
  /^\.void\/knowledge\.json$/,
  /^packages\/cli\/core-assets\//,
  /^packages\/core\/hooks\/_void-hook\.mjs$/,
  /^packages\/core\/hooks\/_syntax-worker\.cjs$/,
  /^packages\/core\/graph\/void-graph\.mjs$/,
];

const SELF = 'test/identity/product-identity.test.ts';
const CODE = /\.(?:[cm]?[jt]s|tsx|sh)$|^\.githooks\//;
const BINARY = /\.(?:png|jpe?g|gif|ico|webp|woff2?|pdf)$/;

function trackedFiles(): string[] {
  return execFileSync('git', ['ls-files', '-z'], { cwd: ROOT, encoding: 'utf8' })
    .split('\0')
    .filter((path) => path !== '' && !BINARY.test(path));
}

function read(path: string): string {
  return readFileSync(resolve(ROOT, path), 'utf8');
}

function readJson(path: string): Record<string, unknown> {
  return JSON.parse(read(path)) as Record<string, unknown>;
}

function holders(paths: readonly string[], needle: string): string[] {
  return paths.filter((path) => read(path).includes(needle));
}

const exempt = (path: string, rules: readonly RegExp[]) => rules.some((rule) => rule.test(path));

describe('the identity source', () => {
  it('reads the same values from TypeScript and from the plain-ESM scripts', () => {
    expect(JSON.parse(JSON.stringify(SCRIPT_IDENTITY))).toEqual(JSON.parse(JSON.stringify(PRODUCT_IDENTITY)));
  });
});

describe('manifests that cannot import the identity', () => {
  it('point every workspace link at the repository', () => {
    const manifest = readJson('package.json');
    expect(manifest['homepage']).toBe(repositoryUrl);
    expect(manifest['repository']).toEqual({ type: 'git', url: `git+${repositoryUrl}.git` });
    expect(manifest['bugs']).toEqual({ url: `${repositoryUrl}/issues` });
  });

  it('publish the CLI under the package name, from this repository', () => {
    const manifest = readJson('packages/cli/package.json');
    expect(manifest['name']).toBe(packageName);
    expect(manifest['homepage']).toBe(`${repositoryUrl}#readme`);
    expect(manifest['repository']).toEqual({
      type: 'git',
      url: `git+${repositoryUrl}.git`,
      directory: 'packages/cli',
    });
    expect(manifest['bugs']).toEqual({ url: `${repositoryUrl}/issues` });
  });

  // `npx <package>` runs the single bin, or every bin when they share one
  // file, or else the bin named after the package; with the deprecated alias
  // in its own file, only a bin bearing the package name keeps `npx` working.
  it('install every declared command and no other, the deprecated ones through their own entry', () => {
    const bin = readJson('packages/cli/package.json')['bin'];
    const expected = Object.fromEntries([
      ...[packageName, commands.primary, ...commands.aliases].map((name) => [name, `./bin/${commands.primary}.mjs`]),
      ...commands.deprecated.map((name) => [name, `./bin/${name}.mjs`]),
    ]);
    expect(bin).toEqual(expected);
  });

  it('link every plugin manifest to the repository', () => {
    const manifests = trackedFiles().filter((path) => path.endsWith('.claude-plugin/plugin.json'));
    expect(manifests.length).toBeGreaterThan(0);
    for (const path of manifests) expect([path, readJson(path)['homepage']]).toEqual([path, repositoryUrl]);
  });
});

describe('workflows, which compare against a literal of their own', () => {
  const workflows = trackedFiles().filter((path) => path.startsWith('.github/workflows/'));

  it('pin every repository guard to the identity slug', () => {
    const guards = workflows.flatMap((path) =>
      [...read(path).matchAll(/^\s*EXPECTED_REPOSITORY:\s*(\S+)\s*$/gm)].map((match) => [path, match[1]]),
    );
    expect(guards.length).toBeGreaterThanOrEqual(5);
    for (const [path, value] of guards) expect([path, value]).toEqual([path, repositorySlug]);
  });

  it('pin the owner and name guards to the identity', () => {
    const promotion = read('.github/workflows/promotion.yml');
    expect(promotion).toMatch(new RegExp(`^\\s*EXPECTED_OWNER: ${repository.owner}$`, 'm'));
    expect(promotion).toMatch(new RegExp(`^\\s*EXPECTED_NAME: ${repository.name}$`, 'm'));
  });

  it('name no repository of the owner other than this one', () => {
    const pattern = new RegExp(`${repository.owner}/([A-Za-z0-9._-]+)`, 'g');
    for (const path of workflows) {
      const others = [...read(path).matchAll(pattern)].map((match) => match[1]).filter((name) => name !== repository.name);
      expect([path, others]).toEqual([path, []]);
    }
  });

  it('spell the package name only in the EXPECTED_PACKAGE variable every step reads', () => {
    for (const path of workflows) {
      const stray = read(path)
        .split('\n')
        .filter((line) => line.includes(packageName) && !/^\s*EXPECTED_PACKAGE:/.test(line));
      expect([path, stray]).toEqual([path, []]);
    }
    const release = read('.github/workflows/release.yml');
    expect(release).toMatch(new RegExp(`^\\s*EXPECTED_PACKAGE: ${packageName}$`, 'm'));
  });
});

describe('literals outside the identity source', () => {
  const files = trackedFiles();

  it('code never spells the repository slug or the package name', () => {
    const code = files.filter((path) => CODE.test(path) && path !== SELF && !exempt(path, GENERATED));
    expect(holders(code, repositorySlug)).toEqual([]);
    expect(code.filter((path) => new RegExp(`(?<![\\w@-])${packageName}(?![\\w-])`).test(read(path)))).toEqual([]);
  });

  it('knows at least one retired name, or this guard would pass on an empty list', () => {
    expect(RETIRED_NAMES.length).toBeGreaterThan(0);
  });

  it.each(RETIRED_NAMES)('%s survives only in the historical record', (retired) => {
    const live = files.filter((path) => path !== SELF && path !== SOURCE && !exempt(path, [...HISTORICAL, ...GENERATED]));
    expect(holders(live, retired)).toEqual([]);
  });
});

/**
 * The product's brand is `commands.primary`; every name in the identity's deprecated lists is a
 * former brand. A reader told to run a deprecated command gets a deprecation notice for following
 * the advice, and a page that names the old product sends them looking for something that no
 * longer exists. The historical record, released or generated bytes and the tests (which have to
 * spell the old names to prove they are still read) keep them; everything else may name a former
 * brand only through one of the declared exceptions below.
 */
describe('former brands outside the identity source', () => {
  const files = trackedFiles();
  const brands = [
    ...PRODUCT_IDENTITY.commands.deprecated,
    ...(readJson(SOURCE)['markers'] as { deprecated: string[] }).deprecated,
    ...PRODUCT_IDENTITY.environment.deprecated.map((prefix) => prefix.replace(/_$/, '')),
  ];
  // `void-harness`, `void harness`, `Void Harness`, `VOID_HARNESS`: one brand, however it is cased.
  const spelling = (brand: string) => brand.split(/[-_ ]/).map((word) => word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  const pattern = new RegExp(
    [...new Set(brands.map((brand) => spelling(brand).join('[-_ ]')))].join('|'),
    'gi',
  );

  const TESTS = [/\.test\.[cm]?[jt]sx?$/, /(^|\/)__(snapshots|fixtures)__\//, /(^|\/)(test\/support|src\/test)\//];
  /** Dated evidence of what was run at the time, under the name it had then. */
  const DATED = [/^docs\/reports\//, /^docs\/[^/]*\d{4}-\d{2}-\d{2}[^/]*\.md$/];
  /** What this repository's own install wrote: released bytes, rewritten by the next published init. */
  const PUBLISHED = [/^\.codex\/hooks\.json$/];
  const PUBLISHED_BLOCK = /<!-- void-harness:begin -->[\s\S]*?<!-- void-harness:end -->/g;

  /**
   * The only places a former brand may still be spelled, each with the reason it cannot move.
   * `token` is removed from the line before the brand is searched for, so an exception never
   * excuses anything else on the same line.
   */
  const DECLARED: readonly { readonly path: RegExp; readonly token: RegExp; readonly why: string }[] = [
    {
      path: /^packages\/(cli|mission-engine|harness-graph|hook-runner)\/src\//,
      token: /void-harness(@\$\{version\})?:mission(\.[a-z-]+)?/g,
      why: 'mission event sources: a wire format in every run journal, compared on read',
    },
    {
      path: /^packages\/mission-engine\/src\/evidence\/command-correction\.ts$/,
      token: new RegExp(
        String.raw`void-harness(?:@[0-9]+\.[0-9]+\.[0-9]+(?:[-+][A-Za-z0-9.+-]+)?)?:mission\.verify`
          .replace(/[.*+?^${}()|[\]\\]/g, '\\$&'),
        'g',
      ),
      why: 'the recovery reader validates the exact released command producer grammar, including its version',
    },
    {
      path: /^(package\.json|packages\/cli\/src\/lib\/self-repo\.ts|scripts\/backlog-index\.mjs)$/,
      token: /(['"])!?void-harness\1/g,
      why: 'the private root package name, which is how the CLI knows it runs in its own source',
    },
    {
      path: /./,
      token: /\d{4}-\d{2}-\d{2}-void-harness-[a-z0-9-]+/g,
      why: 'a historical plan or spec keeps the file name it was written under, and a link to it must resolve',
    },
    {
      path: /^docs\/ARCHITECTURE\.md$/,
      token: /`(VOID_HARNESS_<NAME>|void-harness:mission\.\*)`/g,
      why: 'the architecture names the settings alias and the wire format it deliberately keeps',
    },
    {
      path: /^packages\/cli\/package\.json$/,
      token: /"void-harness": "\.\/bin\/void-harness\.mjs"/g,
      why: 'the deprecated command keeps its own bin so the notice knows how it was invoked',
    },
  ];

  const scanned = files.filter(
    (path) =>
      path !== SELF
      && path !== SOURCE
      && !exempt(path, [...HISTORICAL, ...GENERATED, ...TESTS, ...DATED, ...PUBLISHED])
      && !/^packages\/cli\/bin\/void-harness\.mjs$/.test(path),
  );

  function offences(path: string): string[] {
    const text = /^(CLAUDE|AGENTS)\.md$/.test(path) ? read(path).replace(PUBLISHED_BLOCK, '') : read(path);
    const rules = DECLARED.filter((rule) => rule.path.test(path));
    return text.split('\n').flatMap((line, index) => {
      const residue = rules.reduce((current, rule) => current.replace(rule.token, ''), line);
      return residue.match(pattern) === null ? [] : [`${path}:${index + 1}: ${line.trim().slice(0, 120)}`];
    });
  }

  it('recognizes every spelling of a former brand, or this guard would pass on nothing', () => {
    for (const spelled of ['void-harness init', 'Void Harness', 'VOID_HARNESS_NO_TRIM', 'the void harness']) {
      expect(spelled.match(pattern)).not.toBeNull();
    }
    expect('void-machine harness-graph voidharness'.match(pattern)).toBeNull();
  });

  it('survives only in the historical record, the tests and the declared exceptions', () => {
    expect(scanned.flatMap(offences)).toEqual([]);
  });

  it('keeps each declared exception load-bearing', () => {
    for (const rule of DECLARED) {
      const used = files.some((path) => rule.path.test(path) && new RegExp(rule.token.source).test(read(path)));
      expect([rule.why, used]).toEqual([rule.why, true]);
    }
  });
});
